<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.R16p84w' shared service.

return $this->privates['.service_locator.R16p84w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\WildController::showByCategory' => ['privates', '.service_locator.gEKwHLd', 'get_ServiceLocator_GEKwHLdService.php', true],
    'App\\Controller\\WildController::showByProgram' => ['privates', '.service_locator.yrDeEqb', 'get_ServiceLocator_YrDeEqbService.php', true],
    'App\\Controller\\WildController::showBySeason' => ['privates', '.service_locator.X1wF8Wb', 'get_ServiceLocator_X1wF8WbService.php', true],
    'App\\Controller\\WildController::showEpisode' => ['privates', '.service_locator.dX8oWEV', 'get_ServiceLocator_DX8oWEVService.php', true],
    'App\\Controller\\WildController:showByCategory' => ['privates', '.service_locator.gEKwHLd', 'get_ServiceLocator_GEKwHLdService.php', true],
    'App\\Controller\\WildController:showByProgram' => ['privates', '.service_locator.yrDeEqb', 'get_ServiceLocator_YrDeEqbService.php', true],
    'App\\Controller\\WildController:showBySeason' => ['privates', '.service_locator.X1wF8Wb', 'get_ServiceLocator_X1wF8WbService.php', true],
    'App\\Controller\\WildController:showEpisode' => ['privates', '.service_locator.dX8oWEV', 'get_ServiceLocator_DX8oWEVService.php', true],
], [
    'App\\Controller\\WildController::showByCategory' => '?',
    'App\\Controller\\WildController::showByProgram' => '?',
    'App\\Controller\\WildController::showBySeason' => '?',
    'App\\Controller\\WildController::showEpisode' => '?',
    'App\\Controller\\WildController:showByCategory' => '?',
    'App\\Controller\\WildController:showByProgram' => '?',
    'App\\Controller\\WildController:showBySeason' => '?',
    'App\\Controller\\WildController:showEpisode' => '?',
]);
