<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2I26UlN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2I26UlN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2I26UlN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2I26UlN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2I26UlN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2I26UlN',
    'container.build_id' => '1fb0c0d7',
    'container.build_time' => 1575966790,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2I26UlN');
