<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKu6pRqc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKu6pRqc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKu6pRqc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKu6pRqc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKu6pRqc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ku6pRqc',
    'container.build_id' => '39c5288f',
    'container.build_time' => 1575546308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKu6pRqc');
